from pathlib import Path
from html import escape
from render_research_note import render_note

ROOT = Path(__file__).resolve().parents[1]
(ROOT / 'assets').mkdir(exist_ok=True)

def icon(name):
    paths = {'arrow':'<path d="M4 12h16M14 6l6 6-6 6"/>','search':'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4.5 4.5"/>','github':'<path d="M9 19c-4 1-4-2-6-2m12 5v-4c0-1 .2-2-1-3 4 0 7-2 7-6 0-1-1-3-1-3 0-1 0-3-1-4-2 0-3 1-4 2a12 12 0 0 0-6 0C8 3 6 2 4 2 3 3 3 5 4 6c0 0-1 2-1 3 0 4 3 6 7 6-1 1-1 2-1 3v4"/>','sun':'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>'}
    return f'<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">{paths[name]}</svg>'

def shell(title, active, body, description='iris 的个人博客，记录学习笔记、日常与思考。'):
    nav = ''.join(f'<a href="{url}"'+ (' aria-current="page"' if active==key else '') +f'>{label}</a>' for key,url,label in [('home','index.html','首页'),('notes','notes.html','学习手记'),('about','about.html','关于')])
    return f'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta name="description" content="{escape(description)}"><meta name="robots" content="noindex,nofollow"><title>{escape(title)} · iris 学习手记</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><script src="assets/theme.js"></script><link rel="stylesheet" href="assets/style.css"><script src="assets/site.js" defer></script></head>
<body class="{'home-page' if active == 'home' else 'inner-page'}"><div class="wallpaper-scene" aria-hidden="true"></div><a class="skip" href="#main">跳到正文</a><header class="site-header"><div class="header-inner"><a class="brand" href="index.html" aria-label="iris 学习手记首页"><span class="brand-symbol iris-mark" aria-hidden="true">✳</span><span>iris<span class="brand-sub"> / 学习手记</span></span></a><nav aria-label="主导航">{nav}</nav><a class="github" href="https://github.com/cppywh" target="_blank" rel="noopener noreferrer" aria-label="GitHub（新窗口）">{icon('github')}</a></div></header>
<main id="main">{body}</main><footer class="site-footer"><div><a class="footer-name" href="index.html">iris / 学习手记</a><p>把实验做一遍，把理解写下来。</p></div><div class="footer-right"><span>{icon('sun')} 保持好奇，慢慢生长。</span><small>实验与学习记录 · <a data-wallpaper-source href="https://wallhaven.cc/w/6kqzl6" target="_blank" rel="noopener noreferrer">壁纸来源 ↗</a></small></div></footer><div class="toast" role="status" aria-live="polite"></div></body></html>'''

posts = [
 {'slug':'experiment-notebook','type':'实验记录','tag':'EXPERIMENT','no':'02','title':'一次学习实践，应该留下什么？','desc':'从问题与假设开始，把数据、配置、观察和下一步串成一份可以回看的实验手记。','tags':['学习笔记','实践记录'],'time':'4 分钟','lead':'一次实验结束后，最值得留下的往往不只是一个分数，而是当时的问题、选择，以及后来改变的理解。','sections': [('question','先写下想验证的问题','<p>在运行代码之前，用一句话说明这次实验想验证什么。把目标缩小到一个可以观察的问题，后面的配置与比较才有清晰的依据。</p><blockquote>示例问题：改变某项训练配置后，在相同评估条件下，模型的回答会发生什么变化？</blockquote>'),('setup','给实验留一张配置卡','<p>记录模型、数据划分、训练参数和评估协议。名称之外，还应留下版本或文件标识，方便未来找到同一次运行。</p><div class="table-wrap"><table><thead><tr><th>需要记录</th><th>为什么保留</th></tr></thead><tbody><tr><td>模型与权重版本</td><td>确认比较从哪里开始</td></tr><tr><td>数据划分与去重方式</td><td>说明训练和评估的边界</td></tr><tr><td>参数、随机种子与运行环境</td><td>追踪实验之间的变化</td></tr><tr><td>评估设置与逐题输出</td><td>理解汇总分数之外的差异</td></tr></tbody></table></div>'),('code','把配置写成可阅读的代码','<p>下面仅展示代码块的阅读和复制效果。它是记录格式示例，不会启动训练。</p><div class="code-block"><div class="code-head"><span>Python · 配置记录示例</span><button type="button" class="copy-code">复制代码</button></div><pre><code>experiment = {\n    "question": "写下这次想验证的问题",\n    "changed_variable": "记录本次改动",\n    "seed": 42,\n    "status": "planned",\n}</code></pre></div>'),('observations','把观察和解释分开','<p>“发生了什么”是观察，“为什么发生”是解释。先保留日志和输出，再提出可能的解释；证据不足时，也可以直接写“暂时不确定”。</p><div class="callout"><strong>给未来的自己留一句话</strong><p>这一步我看到什么？它是否支持最初的想法？还有哪一个变量没有控制好？</p></div>'),('next','最后写下下一步','<p>给下一次实验留下一个具体动作：补一个对照、检查一组错误样本，或者先把当前配置重新跑通。</p><p>网站会保留这个位置，方便你逐步补上真实实验、图表和复盘。</p>')]},
 {'slug':'reading-notebook','type':'论文阅读','tag':'READING','no':'03','title':'读一篇论文，也留下一条自己的线索','desc':'问题是什么，方法改变了哪里，哪些结论还想亲手验证。给阅读留一个简单的起点。','tags':['论文阅读','学习方法'],'time':'3 分钟','lead':'读完一篇论文，不必马上写出完整的综述。先留下几个能让自己重新进入问题的线索。','sections':[('question','先记住它想解决什么','<p>用自己的话描述论文的核心问题，再说明这个问题为什么与你正在学习的内容有关。这里将来可以放论文标题、作者和原文链接。</p>'),('method','抓住方法中的关键变化','<p>从输入、训练目标或评估方式里，找出最影响你理解的一处变化。把推导和代码对照起来时，标清哪些是原文内容，哪些是自己的解释。</p><blockquote>一段清楚的解释，可以从“如果拿掉这一步，会发生什么”开始。</blockquote>'),('questions','允许暂时没有答案','<p>把不理解的符号、尚未核对的假设和想复现的细节分别记下来。阅读笔记可以持续更新，不必一次写完。</p>'),('next','把阅读接到下一次尝试','<div class="callout"><strong>下一步的最小动作</strong><p>画出流程、跑一个小例子，或检查实现中的一个函数。选择一个动作，就足够继续。</p></div>')]},
 {'slug':'debug-notebook','type':'问题复盘','tag':'REFLECTION','no':'04','title':'把一次报错，整理成下次能用的笔记','desc':'保留现象、缩小范围、核对原因，再记下真正解决问题的那一步。','tags':['调试','可复现'],'time':'3 分钟','lead':'一次问题解决之后，最容易忘记的是：最初看到了什么，又是什么证据让排查转向了正确的地方。','sections':[('symptom','记录现象，而不只记录结论','<p>留下最小的错误信息、触发条件与环境版本。公开笔记时，用脱敏后的占位值替换凭据和私有地址。</p>'),('isolate','把问题缩到能解释的大小','<p>一次只改变一个影响因素，记录哪些尝试改变了现象，哪些没有。能复现的小例子，通常比一整段运行日志更容易帮助未来的自己。</p>'),('fix','区分暂时绕过和真正修复','<p>写清修改位置、修改理由与验证方式。如果只是绕过，也如实保留尚未解决的问题。</p>'),('next','给下一次排查留一个入口','<div class="callout"><strong>复盘的四行模板</strong><p>现象是什么？怎样稳定触发？最后改了什么？如何确认问题消失？</p></div>')]}
]

featured = {'href':'research/medical-grpo/','type':'实验记录','no':'01','title':'中文医考小模型后训练：从格式学会到答题改进','desc':'从三奖励 GRPO、扩大 SFT 到直接 GRPO 与 DAPO 对照：保留失败结果，用同题数据看变化。','tags':['大模型后训练','GRPO','实验记录'],'time':'项目实录','status':'真实记录'}
grpo_featured = {'href':'research/mini-deepseek-r1-zero/','type':'实验记录','no':'02','title':'纯 GRPO 数学题实验：从 51/100 到 81/100，评估口径也踩了坑','desc':'Qwen3-1.7B-Base 的500步GRPO：同题改对35题、改错5题，保留思考模型44题触顶的评估限制。','tags':['大模型后训练','GRPO','GSM8K'],'time':'项目实录','status':'真实记录'}
all_entries = [grpo_featured, featured, *posts]

def entry(p):
    href = p['href'] if 'href' in p else f"{p['slug']}.html"
    status = p.get('status', '排版示例')
    return f'''<article class="note-row" data-category="{p['type']}" data-search="{escape(p['title']+' '+p['desc']+' '+' '.join(p['tags']))}"><div class="row-index">{p['no']}</div><div class="row-content"><div class="post-meta"><span>{p['type']}</span><span>{status}</span><span>{p['time']}</span></div><h3><a href="{href}">{p['title']}</a></h3><p>{p['desc']}</p><div class="tags">{''.join('<span># '+tag+'</span>' for tag in p['tags'])}</div></div><a href="{href}" class="row-arrow" aria-label="阅读：{p['title']}">{icon('arrow')}</a></article>'''

home = f'''<div class="iris-home"><aside class="identity-panel"><div class="identity-top"><span class="identity-label">A PERSONAL NOTEBOOK</span><span class="edition">EST. 2026</span></div><div class="identity-center"><div class="iris-wordmark"><img src="assets/iris.svg" alt="" aria-hidden="true"><h1>iris<span>.</span></h1></div><p class="identity-subtitle">鸢尾花的学习手记</p><p class="identity-description">心之所向，素履以往，<br>生如逆旅，一苇以航。</p><div class="identity-quote"><span class="quote-rule"></span><p data-season-quote>把好奇种下，等理解开花。</p></div><nav class="identity-nav" aria-label="首页导航"><a href="index.html" aria-current="page">手记<span>01</span></a><a href="notes.html">归档<span>02</span></a><a href="about.html">关于<span>03</span></a></nav></div><div class="theme-picker"><div class="theme-picker-label"><span>今日的底色</span><button type="button" data-next-theme aria-label="切换到下一张壁纸">换一张 ↻</button></div><div class="theme-swatches" role="group" aria-label="选择壁纸主题"><button type="button" data-theme-index="0" aria-label="雕塑 · 雾紫" aria-pressed="false"><span style="--swatch:#796085"></span></button><button type="button" data-theme-index="1" aria-label="机械 · 冰蓝" aria-pressed="false"><span style="--swatch:#2b7483"></span></button><button type="button" data-theme-index="2" aria-label="几何 · 钴蓝" aria-pressed="false"><span style="--swatch:#2468a0"></span></button><button type="button" data-theme-index="3" aria-label="晶体 · 湖青" aria-pressed="false"><span style="--swatch:#58849c"></span></button></div></div><div class="identity-bottom"><a href="https://github.com/cppywh" target="_blank" rel="noopener noreferrer" aria-label="iris 的 GitHub（新窗口）">{icon('github')}<span>GitHub</span></a><span class="bloom-note"><i></i><span data-palette-label>壁纸主题</span></span></div></aside><section class="journal-panel" aria-labelledby="journal-heading"><header class="journal-heading"><div><span class="eyebrow">LEARN / EXPERIMENT / REFLECT</span><h2 id="journal-heading">沿途的记录</h2></div><span class="journal-count">05 / NOTES</span></header><div class="home-preview-note">两篇真实实验记录 · 其余文章为排版示例</div><div class="journal-entries">{''.join(entry(p) for p in all_entries)}</div><a class="journal-more" href="notes.html">翻阅全部手记 {icon('arrow')}</a><div class="journal-postscript"><span>写在页边</span><p>让问题有一个落脚的地方，<br>让每一次尝试，都留下痕迹。</p><small>NOTES TO MY FUTURE SELF</small></div></section><div class="botanical-watermark" aria-hidden="true"></div><div class="floating-seeds" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div></div>'''

notes = f'''<div class="page-wrap"><section class="page-intro"><div class="eyebrow">THE NOTEBOOK</div><h1>学习手记<span class="title-dot">。</span></h1><p>一些实验，一些理解，还有一些暂时没有答案的问题。</p></section><section class="notes-list" aria-label="手记列表"><div class="list-toolbar"><div class="filters" role="group" aria-label="按类型筛选">{''.join(f'<button type="button" data-filter="{name}" aria-pressed="{str(i==0).lower()}">{name}</button>' for i,name in enumerate(['全部','实验记录','论文阅读','问题复盘']))}</div><label class="search-box">{icon('search')}<span class="sr-only">搜索手记</span><input type="search" placeholder="搜索标题、标签…" autocomplete="off" id="note-search"></label></div><div class="list-description"><span>两篇真实记录 · 三篇排版示例</span><span id="result-count" role="status" aria-live="polite">5 篇手记</span></div>{''.join(entry(p) for p in all_entries)}<div class="empty-state" hidden><h2>这一页还是空白。</h2><p>试试其他关键词，或者换一个分类。</p><button class="reset-search" type="button">查看全部手记</button></div></section></div>'''

about = '''<div class="page-wrap"><section class="page-intro"><div class="eyebrow">BEHIND THE NOTES</div><h1>你好，我是 iris<span class="title-dot">。</span></h1><p>正在学习，也正在试着把理解写清楚。</p></section><div class="about-layout"><article class="prose"><div class="preview-note"><span class="preview-dot"></span> 简介为设计占位文案，后续可以修改。</div><h2>为什么叫 iris</h2><p>我的名字是 ywh，也可以读作“鸢尾花”的拼音首字母。鸢尾花的英文是 iris，所以这里就叫 iris。</p><h2>一个可以慢慢积累的地方</h2><p>这里用来存放我的个人笔记：学习中的收获、生活里的片段、遇到的问题，以及慢慢变化的想法。</p><p>有些内容会整理成完整的文章，有些可能只是一段阶段性的理解。希望一段时间后回头看，能知道当时为什么这样做，又在哪里向前走了一步。</p><h2>我想留下什么</h2><ul><li><strong>实验记录</strong>：问题、配置、过程、结果和下一步。</li><li><strong>论文阅读</strong>：重要的线索，以及还想亲手验证的细节。</li><li><strong>问题复盘</strong>：踩过的坑和真正起作用的解决方法。</li></ul><h2>在别处找到我</h2><p><a href="https://github.com/cppywh" target="_blank" rel="noopener noreferrer">我的 GitHub ↗</a></p></article><aside class="about-card"><img class="about-iris" src="assets/iris.svg" alt="鸢尾花插画"><h2>iris</h2><p>学习 · 实验 · 记录</p><div class="about-card-line"></div><span class="tiny-label">CURRENT CHAPTER</span><p>个人笔记 · 学习 · 生活</p><span class="handwritten">Stay curious.</span></aside></div></div>'''

(ROOT/'index.html').write_text(shell('首页','home',home),encoding='utf-8')
(ROOT/'notes.html').write_text(shell('学习手记','notes',notes),encoding='utf-8')
(ROOT/'about.html').write_text(shell('关于','about',about),encoding='utf-8')
for idx,p in enumerate(posts):
    sections=''.join(f'<section id="{sid}"><h2><span class="section-number">{i:02d}</span>{title}</h2>{html}</section>' for i,(sid,title,html) in enumerate(p['sections'],1))
    toc=''.join(f'<a href="#{sid}"><span>{i:02d}</span>{title}</a>' for i,(sid,title,_) in enumerate(p['sections'],1))
    nextpost=posts[(idx+1)%len(posts)]
    body=f'''<div class="reading-progress" aria-hidden="true"></div><div class="page-wrap article-wrap"><a class="back-link" href="notes.html">← 返回学习手记</a><header class="article-header"><div class="eyebrow">{p['tag']} / {p['no']}</div><h1>{p['title']}</h1><p class="article-lead">{p['lead']}</p><div class="post-meta"><span>iris</span><span>{p['type']}</span><span>约 {p['time']}</span><span>排版示例</span></div></header><div class="article-layout"><article class="prose"><div class="preview-note"><span class="preview-dot"></span> 这是页面演示文章，不包含本地笔记或真实实验数据。</div>{sections}<div class="article-end"><span>— END —</span><p>记录到这里，下一步继续。</p></div><a class="next-article" href="{nextpost['slug']}.html"><span>下一篇 · 排版示例</span><strong>{nextpost['title']}</strong>{icon('arrow')}</a></article><aside class="toc"><div class="toc-inner"><span class="eyebrow">本页目录</span><nav aria-label="文章目录">{toc}</nav><a class="back-top" href="#main">↑ 回到顶部</a></div></aside></div></div>'''
    (ROOT/f"{p['slug']}.html").write_text(shell(p['title'],'notes',body,p['desc']),encoding='utf-8')

error_page = shell('页面未找到','', '<div class="page-wrap page-intro"><div class="eyebrow">404 / A MISSING PAGE</div><h1>这一页，还没写到。</h1><p>链接可能已经变化，回到首页继续翻翻吧。</p><a class="text-link" href="/">返回首页 →</a></div>')
for link in ['assets/favicon.svg','assets/style.css','assets/site.js','assets/theme.js','index.html','notes.html','about.html']:
    error_page = error_page.replace('"'+link+'"', '"/'+link+'"')
(ROOT/'404.html').write_text(error_page,encoding='utf-8')
(ROOT/'.nojekyll').touch()
render_note(ROOT, shell, icon)
render_note(ROOT, shell, icon, slug="mini-deepseek-r1-zero", eyebrow="GRPO / 02", lead="500步纯GRPO，同题净增30个百分点；同时复盘截断、解析和条件准确率。", legacy=False)
print('Built the static site and single medical GRPO note. No private notebook data imported.')


